# Generated by Django 3.1 on 2020-11-16 19:20

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('Codigo_estilo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30, null=True)),
                ('ruta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Codigo_menu', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_Menu', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Climatic.estilo')),
                ('Nombre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Climatic.menu')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesMenu',
            fields=[
                ('Codigo_Opcion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Opcion', models.CharField(max_length=35)),
                ('Codigo_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_Climatic.menu')),
            ],
        ),
        migrations.CreateModel(
            name='articulo_Cientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('estado', models.IntegerField(choices=[(0, 'borrador'), (1, 'Publicado')], default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posteo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creacion'],
            },
        ),
    ]
