# Generated by Django 3.1 on 2020-11-16 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web_Climatic', '0002_auto_20201116_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_cientifico',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posteo', to=settings.AUTH_USER_MODEL),
        ),
    ]
