# Generated by Django 3.1 on 2020-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Climatic', '0003_auto_20201116_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo_cientifico',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
