# Generated by Django 3.1 on 2020-11-18 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web_Climatic', '0005_auto_20201118_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
