# Generated by Django 3.1 on 2020-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Climatic', '0006_auto_20201118_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('Codigo_pregunta', models.BigAutoField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=150, unique=True)),
                ('respuesta', models.TextField()),
            ],
        ),
    ]
