# Generated by Django 3.1 on 2020-11-23 16:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Climatic', '0011_auto_20201123_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='respuesta',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
