# Generated by Django 3.1 on 2020-11-24 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_Climatic', '0013_opcionesmenu_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Estilo',
            field=models.ForeignKey(default=({'Codigo_estilo': 1},), on_delete=django.db.models.deletion.CASCADE, to='Web_Climatic.estilo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=({'Codigo_menu': 3},), on_delete=django.db.models.deletion.CASCADE, to='Web_Climatic.menu'),
        ),
    ]
